### ISSUE TITLE
Quit the java process when cider exits

### ISSUE THREAD

**Issue by harindu95** [kovrik/cider-diet#2]
As it is now, It doesn't exit the java process when it leaves.

**Comment by kovrik** [comment]
@harindu95 
Hi!
I thought they've fixed all issues in the original cider already :)
Are there any reasons to use `cider-diet` today?

If yes, I'll have a look at the issue this week (hopefully).

Thanks!

**Comment by kovrik** [comment]
@harindu95 
Hi!
I've just updated dependencies (to the latest versions). Please check it out.

Regarding stale java process on cider-quit: behaviour is the same for the original cider.
That is because cider-nrepl is supposed to be used as a standalone server.
So, if you lost cider-nrepl connection, then you can just call `cider-connect` that will connect to the running server instance.

If you run the process from Emacs (via `cider-diet-jack-in` command), then Emacs will stop all child processes on exit. Or you can use `list-processes` to stop it manually.
